name: library_distributed_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_svg: ^2.2.0
  chopper: ^8.1.0
  dio: ^5.8.0+1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  json_annotation: ^4.9.0
  logger: ^2.6.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  riverpod: ^2.6.1
  toastification: ^3.0.3
  google_fonts: ^6.3.0
  result_dart: ^2.1.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  chopper_generator: ^8.1.0
  json_serializable: ^6.9.5
  go_router_builder: ^2.3.0
  build_verify: ^3.1.1

flutter:
  uses-material-design: true
